eth-infinitism/bundler

.idea/aa-bundler.iml
.idea/misc.xml
dockers/bundler/dbuild.sh
dockers/docker-compose.yml
lerna.json
packages/bundler/package.json
packages/bundler/src/BundlerServer.ts
packages/bundler/src/UserOpMethodHandler.ts
packages/bundler/src/runner/runop.ts
packages/bundler/test/Flow.test.ts
packages/bundler/test/UserOpMethodHandler.test.ts
packages/sdk/package.json
packages/sdk/src/BaseWalletAPI.ts
packages/sdk/src/ClientConfig.ts
packages/sdk/src/DeterministicDeployer.ts
packages/sdk/src/ERC4337EthersProvider.ts
packages/sdk/src/HttpRpcClient.ts
packages/sdk/src/PaymasterAPI.ts
packages/sdk/src/Provider.ts
packages/sdk/src/SimpleWalletAPI.ts
packages/sdk/test/0-deterministicDeployer.test.ts
packages/sdk/test/3-ERC4337EthersSigner.test.ts
packages/utils/package.json
packages/utils/src/postExecCheck.ts

paymasterAPI
remove unused chainID
remove unused dependencies (hardhat)

API updates

---

packages/sdk/src/calcPreVerificationGas.ts
packages/sdk/test/4-calcPreVerificationGas.test.ts

Add sigSize to calcPreVerificationGas

---

README.md
packages/bundler/src/BundlerConfig.ts
packages/bundler/src/modules/ValidationManager.ts
packages/bundler/src/modules/initServer.ts
packages/bundler/src/runBundler.ts
packages/bundler/src/runner/runop.ts
packages/bundler/test/UserOpMethodHandler.test.ts
packages/bundler/test/ValidateManager.test.ts
packages/utils/package.json

require "unsafe" flag to run without geth
(normal validation requires geth-specific debug_traceCall)

AA-95 add unsafe flag

---

packages/bundler/deploy/2-deploy-entrypoint.ts
packages/bundler/src/BundlerConfig.ts
packages/bundler/src/BundlerServer.ts
packages/bundler/src/runner/runop.ts
packages/sdk/src/DeterministicDeployer.ts

Also fixing sendBundleNow() empty rpc object when no op is bundled.

Deploying BundlerHelper

---

packages/bundler/src/modules/ValidationManager.ts

Related: https://github.com/eth-infinitism/account-abstraction/pull/166

Check for sigFailed in simulation results

---

packages/bundler/src/BundlerCollectorTracer.ts
packages/bundler/src/GethTracer.ts
packages/bundler/src/runner/runop.ts
packages/bundler/src/utils.ts
packages/bundler/test/UserOpMethodHandler.test.ts
packages/bundler/test/tracer.test.ts

- tracer language doesn't support `backquote`, let and const.

change code to be BOR-compatible

---

README.md

Related to Issue #69 
Updated the documentation of the "Usage" section to avoid certain errors due to inaccurate steps.

README: update usage

---

packages/sdk/src/index.ts

Expose BaseAccountAPI for more flexibility on 4337 integration

---

packages/bundler/src/modules/ReputationManager.ts

Fix calculation of minimum amount of ops to be included

---

package.json
packages/bundler/src/Config.ts
packages/bundler/src/runner/runop.ts

fix bundler --network

---

packages/bundler/src/RpcTypes.ts
packages/bundler/src/UserOpMethodHandler.ts
packages/bundler/test/UserOpMethodHandler.test.ts
packages/sdk/src/HttpRpcClient.ts

mistakenly named "verificationGas"

fix typo: rename verificationGas to verificationGasLimit

---

.github/workflows/build.yml
packages/bundler/localconfig/bundler.config.json
packages/bundler/src/UserOpMethodHandler.ts
packages/bundler/test/UserOpMethodHandler.test.ts
yarn.lock

default values are for missing values, and should not override user-specified values.
(reported by: https://t.me/sherifabdelmoatty)

bugfix: estimateUserOperationGas gas values are overridden by the default values

---

packages/bundler/contracts/tests/TestTimeRangeAccount.sol
packages/bundler/src/modules/Types.ts
packages/bundler/src/modules/ValidationManager.ts
packages/bundler/test/ValidateManager.test.ts

fix bundler check for "expire too soon"

---

packages/bundler/src/modules/MempoolManager.ts

fix: debug_bundler_clearState clears MempoolManager.entryCount

---

packages/bundler/src/parseScannerResult.ts

Validation in https://github.com/eth-infinitism/bundler-spec-tests/pull/31

AA-182: Detect violation of rule "4.1 Must not use value" in the bundler

---

dockers/bundler/dbuild.sh
packages/bundler/package.json

- verificationGasLimit field name fix.

bundler 0.6.1

---

packages/bundler/src/modules/EventsManager.ts

fix the bug that failed to include address

fix: reputation bug

---

scripts/checkRulesCoverage

unknown rule: don't throw exception, just add to report (once)

fix checkRulesCoverage

---

packages/validation-manager/src/TracerResultParser.ts

Removing EREP-050 rule after removing second postOp

Allowing unstaked paymaster to return a context

---

packages/bundler/src/modules/ReputationManager.ts

tolower address
accept numbers as numeric or hex

debug_setReputation: relax params

---

packages/bundler/src/modules/BundleManager.ts

- blame staked sender for pm, factory failures
- blame staked factory for sender error

EREP-020, EREP-030 

---

.github/workflows/build.yml
packages/validation-manager/src/ValidationManager.ts

AA-497 validate-7702-state-override

---

packages/validation-manager/src/ValidationManager.ts

not needed: geth node supports authorizationList in eth_call and debug_traceCall

Remove EIP-7702 stateOverride
